spring.application.name=Detection_Maladie-Service
server.port=8058

spring.datasource.url=jdbc:mysql://db-detection:3306/detection_maladie_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.cloud.config.enabled=false

ia.flask.url=http://flask-ia:5000

spring.ai.openai.api-key=NONE
spring.ai.openai.chat.enabled=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload-dir=/uploads/mri

dossier.medical.url=http://dossier-medical-service:8059