# Profil LOCAL (sans Docker)
# Lancer avec: -Dspring.profiles.active=local

# MongoDB local (sans authentification)
spring.mongodb.uri=mongodb://localhost:27017/rayen

# Eureka local
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
