# Profil DOCKER - Tracking Service
spring.application.name=Tracking-Service
server.port=9011

# MySQL Docker
spring.datasource.url=jdbc:mysql://db-tracking:3306/db_tracking?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Eureka Docker
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
