spring.application.name=Detection_Maladie-Service
server.port=8058

# ???????????????????????????????????
#          BASE DE DONN�ES
# ???????????????????????????????????
spring.datasource.url=jdbc:mysql://localhost:3306/detection_maladie_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ???????????????????????????????????
#           JPA / Hibernate
# ???????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ???????????????????????????????????
#          SPRING CLOUD
# ???????????????????????????????????
spring.cloud.config.enabled=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ???????????????????????????????????
#          URL Flask IA
# ???????????????????????????????????
ia.flask.url=http://localhost:5000

# ???????????????????????????????????
#          Spring AI (d�sactiv�)
# ???????????????????????????????????
spring.ai.openai.api-key=NONE
spring.ai.openai.chat.enabled=false

# ???????????????????????????????????
#          Upload image
# ???????????????????????????????????
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload-dir=${user.home}/softcare-uploads/mri

# ???????????????????????????????????
#          Dossier Medical URL
# ???????????????????????????????????
dossier.medical.url=http://localhost:8059