# Profil DOCKER - Group Service
spring.application.name=group-service
server.port=8097

# MySQL Docker
spring.datasource.url=jdbc:mysql://db-group:3306/group_service_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Eureka Docker
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
