apiVersion: v1
kind: ConfigMap
metadata:
  name: fakarni-config
  namespace: fakarni
data:
  EUREKA_URL: "http://eureka-server:8761/eureka/"
  SPRING_PROFILES_ACTIVE: "docker"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  FACEBOOK_GRAPH_API_VERSION: "v21.0"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
