apiVersion: v1
kind: Secret
metadata:
  name: fakarni-secrets
  namespace: fakarni
type: Opaque
stringData:
  MAIL_USERNAME_USER: "mohamadrayen.jbili@esprit.tn"
  MAIL_PASSWORD_USER: "ueivocwsiczztvem"
  MAIL_USERNAME: "bahri.rania098@gmail.com"
  MAIL_PASSWORD: "cfbyuwbpasuwnxvj"
  GOOGLE_CLIENT_ID: "968599520946-llp69cv61a73f9457lpedn7m4tflrr2t.apps.googleusercontent.com"
  FACEBOOK_APP_ID: "1270980888473415"
  FACEBOOK_APP_SECRET: "your-facebook-app-secret-here"
  TWILIO_ACCOUNT_SID: "AC67b937e03fdc6d358fe90c94866ca636"
  TWILIO_AUTH_TOKEN: "5129a79de1a2e8c4e4a917dbc4f25f0a"
  TWILIO_FROM_NUMBER: "+16812708324"
  MAILTRAP_USERNAME: "your-mailtrap-username"
  MAILTRAP_PASSWORD: "your-mailtrap-password"
  JWT_SECRET: "ZHVtbXktc2VjcmV0LXNlY3JldC1zZWNyZXQtc2VjcmV0LXNlY3JldC1zZWNyZXQ="
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "admin"
  MYSQL_ROOT_PASSWORD: "root"
