spring.application.name=Eureka-Service
server.port=8761

# EUREKA SERVER (standalone en local)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0

# ACTUATOR
management.endpoints.web.exposure.include=health,info