# Profil DOCKER - Chat Service
spring.application.name=Chat-Service
server.port=8070

# MongoDB Docker
spring.data.mongodb.uri=mongodb://admin:admin@mongodb:27017/chat_db?authSource=admin

# Eureka Docker
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# WebSocket
spring.websocket.allowed-origins=*
