server.port=8070

# MongoDB Configuration (Local MongoDB without authentication)
spring.data.mongodb.uri=mongodb://localhost:27017/chat_db

# Application Name
spring.application.name=Chat-Service

# Disable Spring Cloud Config
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# Eureka Registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
